[package]
name = "grpc"
version = "0.1.0"
edition = "2018"
authors = ["Abhinandan Purkait <abhinandan.purkait@mayadata.io>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "0.5.2"
prost = "0.8.0"
prost-types = "0.8.0"
tokio = { version = "1.12.0", features = ["full"] }
common-lib = { path = "../../common" }
humantime = "2.1.0"
utils = { path = "../../utils/utils-lib" }
rpc = { path = "../../rpc"}
# Tracing
tracing-subscriber = "0.2.24"
tracing-opentelemetry = "0.15.0"
opentelemetry = { version = "0.16.0", features = ["rt-tokio-current-thread"] }
opentelemetry-http = { version = "0.5.0" }
opentelemetry-semantic-conventions = "0.8.0"
tracing = "0.1.28"
http-body = "0.4.4"
tower = { version = "0.4.8", features = [ "timeout", "util" ] }
serde_json = "1.0.81"

[build-dependencies]
tonic-build = "0.5.2"
prost-build = "0.8.0"

[dev-dependencies]
once_cell = "1.9.0"