[package]
name = "rest"
description = "Control plane REST server"
version = "1.0.0"
authors = ["Tiago Castro <tiago.castro@mayadata.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "rest"
path = "./service/src/main.rs"

[lib]
name = "rest_client"
path = "./src/lib.rs"

[dependencies]
# Actix Server, telemetry
rustls = "0.20.0"
rustls-pemfile = "0.2.1"
actix-web = { version = "4.0.0-beta.9", features = ["rustls"] }
actix-service = "2.0.0"
opentelemetry-jaeger = { version = "0.15.0", features = ["rt-tokio-current-thread"] }
tracing-opentelemetry = "0.15.0"
opentelemetry = { version = "0.16.0", features = ["rt-tokio-current-thread"] }
actix-web-opentelemetry = "0.11.0-beta.5"
tracing = "0.1.28"
tracing-subscriber = "0.2.24"
once_cell = "1.9.0"
async-trait = "0.1.51"
serde_json = { version = "1.0.68", features = ["preserve_order"] }
serde_yaml = "0.8.21"
structopt = "0.3.23"
futures = "0.3.17"
anyhow = "1.0.44"
snafu = "0.6.10"
url = "2.2.2"
http = "0.2.5"
tinytemplate = "1.2.1"
jsonwebtoken = "7.2.0"
common-lib = { path = "../../common" }
utils = { path = "../../utils/utils-lib" }
humantime = "2.1.0"
git-version = "0.3.5"
grpc = { path = "../grpc" }

[dev-dependencies]
tokio = { version = "1.12.0", features = ["full"] }
composer = { path = "../../utils/dependencies/composer", default-features = false }
deployer-cluster = { path = "../../utils/deployer-cluster" }

[dependencies.serde]
features = ["derive"]
version = "1.0.130"
