apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: $NAMESPACE
spec:
  strategy: allInOne
  ingress:
    enabled: false
  query:
    serviceType: NodePort
    nodePort: 30012
  storage:
    type: memory
    options:
      memory:
        max-traces: 100000
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: In
              values:
              - ""
  tolerations:
    - key: node-role.kubernetes.io/master
    - key: node-role.kubernetes.io/control-plane