[package]
name = "csi-driver"
description = "CSI controller"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "csi-controller"
path = "controller/src/main.rs"

[[bin]]
name = "csi-node"
path = "node/src/main.rs"

[build-dependencies]
tonic-build = "0.5.2"
prost-build = "0.8.0"

[dependencies]
anyhow = "1.0.44"
async-stream = "0.3.2"
futures = { version = "0.3.17", default-features = false }
humantime = "2.1.0"
once_cell = "1.8.0"
regex = "1.5.4"
rpc = { path = "../../rpc" }
tokio = { version = "1.12.0", features = ["full"] }
tokio-stream = { version = "0.1.7", features = ["net"] }
tonic = "0.5.2"
clap = "2.33.3"

# Tracing
tracing = "0.1.28"
tracing-subscriber = "0.2.24"
opentelemetry-jaeger = { version = "0.15.0", features = ["rt-tokio-current-thread"] }
tracing-opentelemetry = "0.15.0"
opentelemetry = { version = "0.16.0", features = ["rt-tokio-current-thread"] }

async-trait = "0.1.51"
chrono = "0.4.19"
failure = "0.1.8"
glob = "0.3.0"
lazy_static = "1.4.0"
prost = "0.8.0"
prost-derive = "0.8.0"
prost-types = "0.8.0"
serde_json = "1.0.68"
snafu = "0.6.10"
sys-mount = "1.3.0"
tower = { version = "0.4.8", features = [ "timeout", "util" ] }
udev = "0.6.2"
url = "2.2.2"
uuid = { version = "0.8.2", features = ["v4"] }
which = "4.2.2"
k8s-openapi = { version = "0.13.0", default-features = false, features = ["v1_20"] }
kube = { version = "0.60.0", features = ["derive"] }
devinfo = { path = "../../utils/dependencies/devinfo" }
nvmeadm = { path = "../../utils/dependencies/nvmeadm" }
sysfs = { path = "../../utils/dependencies/sysfs" }
common-lib = { path = "../../common" }
utils = { path = "../../utils/utils-lib" }
shutdown = { path = "../../utils/shutdown" }

[dependencies.serde]
features = ["derive"]
version = "1.0.130"
